//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

import Testing

@testable import SparkConnect

/// A test suite for `ConditionalFunctions`
@Suite(.serialized)
struct ConditionalFunctionsTests {

  @Test
  func conditionalFunctions() throws {
    for (column, name) in [
      (nullifzero(col("a")), "nullifzero"),
      (zeroifnull(col("a")), "zeroifnull"),
    ] {
      let expr = column.expr
      #expect(expr.unresolvedFunction.functionName == name)
      #expect(expr.unresolvedFunction.arguments[0].unresolvedAttribute.unparsedIdentifier == "a")
    }

    for (column, name) in [
      (coalesce(col("a"), col("b")), "coalesce"),
      (ifnull(col("a"), col("b")), "ifnull"),
      (nanvl(col("a"), col("b")), "nanvl"),
      (nullif(col("a"), col("b")), "nullif"),
      (nvl(col("a"), col("b")), "nvl"),
    ] {
      let expr = column.expr
      #expect(expr.unresolvedFunction.functionName == name)
      #expect(expr.unresolvedFunction.arguments.count == 2)
      #expect(expr.unresolvedFunction.arguments[0].unresolvedAttribute.unparsedIdentifier == "a")
      #expect(expr.unresolvedFunction.arguments[1].unresolvedAttribute.unparsedIdentifier == "b")
    }

    let coalesced = coalesce(col("a"), col("b"), col("c")).expr
    #expect(coalesced.unresolvedFunction.functionName == "coalesce")
    #expect(coalesced.unresolvedFunction.arguments.count == 3)

    let nvl2Expr = nvl2(col("a"), col("b"), col("c")).expr
    #expect(nvl2Expr.unresolvedFunction.functionName == "nvl2")
    #expect(nvl2Expr.unresolvedFunction.arguments.count == 3)
  }

  @Test
  func whenFunction() throws {
    let expr = when(col("a") > 1, lit(10)).expr
    #expect(expr.unresolvedFunction.functionName == "when")
    #expect(expr.unresolvedFunction.arguments.count == 2)

    let chained = try when(col("a") > 2, 10).when(col("a") > 1, 20).otherwise(0).expr
    #expect(chained.unresolvedFunction.functionName == "when")
    #expect(chained.unresolvedFunction.arguments.count == 5)
    #expect(chained.unresolvedFunction.arguments[1].literal.long == 10)
    #expect(chained.unresolvedFunction.arguments[3].literal.long == 20)
    #expect(chained.unresolvedFunction.arguments[4].literal.long == 0)
  }

  @Test
  func whenMisuse() throws {
    // `when`/`otherwise` can only be applied on a column generated by `when`.
    #expect(throws: SparkConnectError.InvalidArgument) {
      try col("a").when(col("b") > 1, 1)
    }
    #expect(throws: SparkConnectError.InvalidArgument) {
      try col("a").otherwise(1)
    }
    // `when`/`otherwise` cannot be applied once `otherwise` is applied.
    #expect(throws: SparkConnectError.InvalidArgument) {
      try when(col("a") > 1, 1).otherwise(2).when(col("a") > 0, 3)
    }
    #expect(throws: SparkConnectError.InvalidArgument) {
      try when(col("a") > 1, 1).otherwise(2).otherwise(3)
    }
  }

  @Test
  func selectConditionalFunctions() async throws {
    let spark = try await SparkSession.builder.getOrCreate()
    let df = try await spark.sql(
      "SELECT * FROM VALUES (1, 10), (CAST(NULL AS INT), 20) T(a, b)")
    #expect(try await df.select(coalesce(col("a"), col("b"))).collect() == [Row(1), Row(20)])
    #expect(try await df.select(ifnull(col("a"), col("b"))).collect() == [Row(1), Row(20)])
    #expect(try await df.select(nvl(col("a"), col("b"))).collect() == [Row(1), Row(20)])
    #expect(
      try await df.select(nvl2(col("a"), lit("yes"), lit("no"))).collect()
        == [Row("yes"), Row("no")])
    #expect(try await df.select(nullif(col("b"), lit(10))).collect() == [Row(nil), Row(20)])

    let doubles = try await spark.sql("SELECT CAST('NaN' AS DOUBLE) AS a, 1.0D AS b")
    #expect(try await doubles.select(nanvl(col("a"), col("b"))).collect() == [Row(1.0)])
    #expect(try await doubles.select(nanvl(col("b"), col("a"))).collect() == [Row(1.0)])
    await spark.stop()
  }

  @Test
  func selectNullifzeroAndZeroifnull() async throws {
    let spark = try await SparkSession.builder.getOrCreate()
    if await isSparkVersionAtLeast(spark.version, "4.0.0") {
      let df = try await spark.sql(
        "SELECT * FROM VALUES (0, CAST(NULL AS INT)), (1, 2) T(a, b)")
      #expect(try await df.select(nullifzero(col("a"))).collect() == [Row(nil), Row(1)])
      #expect(try await df.select(zeroifnull(col("b"))).collect() == [Row(0), Row(2)])
    }
    await spark.stop()
  }

  @Test
  func selectWhenOtherwise() async throws {
    let spark = try await SparkSession.builder.getOrCreate()
    let df = try await spark.range(4)
    let rows = try await df.select(
      when(col("id") < 1, "zero").when(col("id") < 3, "few").otherwise("many").alias("group")
    ).collect()
    #expect(rows == [Row("zero"), Row("few"), Row("few"), Row("many")])

    // Without `otherwise`, null is returned for unmatched conditions.
    let nullable = try await df.select(when(col("id") == 0, "zero").alias("group")).collect()
    #expect(nullable == [Row("zero"), Row(nil), Row(nil), Row(nil)])
    await spark.stop()
  }
}
